"""
Platform runner for Neogeo
Generated by showet-scaffold
"""

from PlatformBase import PlatformBase

class PlatformNeogeo(PlatformBase):
    def __init__(self):
        super().__init__()
        self.platform_name = "neogeo"
        self.core = "fbneo"
        self.emulator = "fbneo"
    
    def get_rom_path(self, demo_info):
        return f"{demo_info.get('platform_path', 'roms/neogeo')}"
    
    def get_shader(self):
        return "crt/crt-easymode"
    
    def get_display_config(self):
        return {
            'width': 320,
            'height': 224,
            'fullscreen': True
        }
