"""
Platform runner for Neogeo
Generated by showet-scaffold
"""

from PlatformBase import PlatformBase

class PlatformNeogeo(PlatformBase):
    def __init__(self):
        super().__init__("neogeo", version="1.0.0-scaffold")
        self.emulators = ["retroarch"]
        self.cores = ["fbneo"]
    
    def get_rom_path(self, demo_info):
        return f"{demo_info.get('platform_path', 'roms/neogeo')}"
    
    def get_shader(self):
        return "crt/crt-easymode"
    
    def get_display_config(self):
        return {
            'width': 320,
            'height': 224,
            'fullscreen': True
        }
