#!/usr/bin/env python3
"""
Showet Scaffold - Platform Addition CLI Tool
Generates boilerplate files for new demo platforms
"""

import os
import sys
import argparse
from pathlib import Path

PLATFORM_TEMPLATE = '''"""
Platform runner for {platform_name}
Generated by showet-scaffold
"""

from PlatformBase import PlatformBase

class Platform{platform_class}(PlatformBase):
    def __init__(self):
        super().__init__()
        self.platform_name = "{platform_key}"
        self.core = "{core}"
        self.emulator = "{emulator}"
    
    def get_rom_path(self, demo_info):
        return f"{{demo_info.get('platform_path', 'roms/{platform_key}')}}"
    
    def get_shader(self):
        return "{shader}"
    
    def get_display_config(self):
        return {{
            'width': {width},
            'height': {height},
            'fullscreen': True
        }}
'''

CONFIG_TEMPLATE = '''{{
    "platform": "{platform_key}",
    "core": "{core}",
    "emulator": "{emulator}",
    "shader": "{shader}",
    "display": {{
        "width": {width},
        "height": {height}
    }},
    "sound": {{
        "type": "{sound}"
    }}
}}
'''

SHADER_TEMPLATE = '''// {platform_name} CRT Shader
// Generated by showet-scaffold

precision mediump float;

uniform sampler2D u_texture;
varying vec2 v_texCoord;

void main() {{
    vec2 coord = v_texCoord;
    
    // Simple scanlines
    float scanline = sin(coord.y * {scanline_density}) * {scanline_intensity};
    
    vec4 color = texture2D(u_texture, coord);
    gl_FragColor = vec4(color.rgb - scanline, color.a);
}}
'''

PLATFORM_CONFIGS = {
    "neogeo": {"core": "fbneo", "emulator": "fbneo", "shader": "crt/crt-easymode", "width": 320, "height": 224, "sound": "8-bit"},
    "sg32x": {"core": "picodrive", "emulator": "picodrive", "shader": "crt/crt-pi", "width": 320, "height": 224, "sound": "16-bit"},
    "pcengine": {"core": "mednafen_pce_fast", "emulator": "mednafen", "shader": "crt/crt-royale", "width": 320, "height": 240, "sound": "8-bit"},
    "vectrex": {"core": "vecx", "emulator": "vecx", "shader": "vector/vector-glow", "width": 480, "height": 490, "sound": "analog"},
    "zxs48k": {"core": "fuse", "emulator": "fuse", "shader": "crt/crt-pi", "width": 256, "height": 192, "sound": "beeper"}
}

def create_platform_runner(platform_key: str, output_dir: str):
    """Generate Platform_*.py file for new platform"""
    if platform_key not in PLATFORM_CONFIGS:
        print(f"❌ Unknown platform: {platform_key}")
        print(f"Available platforms: {', '.join(PLATFORM_CONFIGS.keys())}")
        return False
    
    config = PLATFORM_CONFIGS[platform_key]
    platform_name = platform_key.replace('_', ' ').title()
    platform_class = ''.join(word.capitalize() for word in platform_key.split('_'))
    
    # Get base directory
    base = Path(output_dir)
    
    # Create platform runner
    runner_content = PLATFORM_TEMPLATE.format(
        platform_name=platform_name,
        platform_class=platform_class,
        platform_key=platform_key,
        core=config["core"],
        emulator=config["emulator"],
        shader=config["shader"],
        width=config["width"],
        height=config["height"]
    )
    
    runner_path = base / f"Platform_{platform_key}.py"
    runner_path.write_text(runner_content)
    print(f"✅ Created: {runner_path}")
    
    # Create nostalgist config
    config_content = CONFIG_TEMPLATE.format(platform_key=platform_key, **config)
    config_path = base / "nostalgist_configs" / f"{platform_key}.json"
    config_path.parent.mkdir(exist_ok=True)
    config_path.write_text(config_content)
    print(f"✅ Created: {config_path}")
    
    # Create shader stub
    shader_content = SHADER_TEMPLATE.format(
        platform_name=platform_name,
        scanline_density=200,
        scanline_intensity=0.1
    )
    shader_path = base / "shaders" / f"{platform_key}_scanlines.glsl"
    shader_path.parent.mkdir(exist_ok=True)
    shader_path.write_text(shader_content)
    print(f"✅ Created: {shader_path}")
    
    return True

def main():
    parser = argparse.ArgumentParser(
        description="Showet Platform Scaffold",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 showet-scaffold.py neogeo
  python3 showet-scaffold.py pcengine
  python3 showet-scaffold.py --list
        """
    )
    
    parser.add_argument('platform', nargs='?', help='Platform key to scaffold')
    parser.add_argument('--list', action='store_true', help='List available platforms')
    parser.add_argument('--dir', default='.', help='Output directory')
    
    args = parser.parse_args()
    
    if args.list:
        print("📋 Available platform templates:")
        for key in PLATFORM_CONFIGS:
            config = PLATFORM_CONFIGS[key]
            print(f"  {key:12} - core: {config['core']}, resolution: {config['width']}x{config['height']}")
        return
    
    if not args.platform:
        parser.print_help()
        return
    
    print(f"🚀 Scaffolding platform: {args.platform}")
    if create_platform_runner(args.platform, args.dir):
        print(f"\n🎉 {args.platform} platform added successfully!")
        print("   Don't forget to:")
        print("   - Add ROM files to the platform directory")
        print("   - Test with: python3 showet.py <demo_id> --platform {args.platform}")

if __name__ == "__main__":
    main()