#!/usr/bin/env python3
"""
Showet Scaffold - Platform Addition CLI Tool
Generates boilerplate files for new demo platforms
"""

import argparse
import json
import sys
from pathlib import Path

PLATFORM_TEMPLATE = '''"""
Platform runner for {platform_name}
Generated by showet-scaffold

NOTE: This is a scaffold. The abstract methods required by PlatformBase are
stubbed so the runner imports and instantiates cleanly; replace them with real
emulation logic before shipping.
"""

from __future__ import annotations

from typing import Any

from PlatformBase import PlatformBase


class Platform{platform_class}(PlatformBase):
    def __init__(self):
        super().__init__("{platform_key}", version="1.0.0-scaffold")
        self.emulators = ["retroarch"]
        self.cores = ["{core}"]
        self.extensions = ["zip"]

    def supported_platforms(self) -> list[str]:
        return ["{platform_key}"]

    def initialize(self) -> bool:
        self._is_initialized = True
        return True

    def load_game(self, rom_path: str) -> bool:
        if not self.is_initialized():
            return False
        self._last_rom_path = rom_path
        return True

    def run_frame(self, controls: dict[str, Any]) -> bool:
        if not self.is_initialized() or not self._last_rom_path:
            return False
        return True

    def get_status_report(self) -> dict[str, Any]:
        return {{
            "platform": self.platform_name,
            "initialized": self.is_initialized(),
            "current_rom": self._last_rom_path or "none",
        }}

    def save_state(self) -> bytes:
        return b""

    def load_state(self, state_data: bytes) -> bool:
        return True

    def get_rom_path(self, demo_info):
        return f"{{demo_info.get('platform_path', 'roms/{platform_key}')}}"

    def get_shader(self):
        return "{shader}"

    def get_display_config(self):
        return {{
            'width': {width},
            'height': {height},
            'fullscreen': True,
        }}
'''

CONFIG_TEMPLATE = '''{{
    "platform": "{platform_key}",
    "core": "{core}",
    "emulator": "{emulator}",
    "shader": "{shader}",
    "display": {{
        "width": {width},
        "height": {height}
    }},
    "sound": {{
        "type": "{sound}"
    }}
}}
'''

SHADER_TEMPLATE = '''// {platform_name} CRT Shader
// Generated by showet-scaffold

precision mediump float;

uniform sampler2D u_texture;
varying vec2 v_texCoord;

void main() {{
    vec2 coord = v_texCoord;
    
    // Simple scanlines
    float scanline = sin(coord.y * {scanline_density}) * {scanline_intensity};
    
    vec4 color = texture2D(u_texture, coord);
    gl_FragColor = vec4(color.rgb - scanline, color.a);
}}
'''

PLATFORM_CONFIGS = {
    "neogeo": {"core": "fbneo", "emulator": "fbneo", "shader": "crt/crt-easymode", "width": 320, "height": 224, "sound": "8-bit"},
    "sg32x": {"core": "picodrive", "emulator": "picodrive", "shader": "crt/crt-pi", "width": 320, "height": 224, "sound": "16-bit"},
    "pcengine": {"core": "mednafen_pce_fast", "emulator": "mednafen", "shader": "crt/crt-royale", "width": 320, "height": 240, "sound": "8-bit"},
    "vectrex": {"core": "vecx", "emulator": "vecx", "shader": "vector/vector-glow", "width": 480, "height": 490, "sound": "analog"},
    "zxs48k": {"core": "fuse", "emulator": "fuse", "shader": "crt/crt-pi", "width": 256, "height": 192, "sound": "beeper"}
}

def verify_platform_runner(runner_path: Path, platform_key: str) -> tuple[bool, str]:
    """Import the generated Platform module and prove it is a usable PlatformBase subclass.

    Returns ``(ok, message)``. This converts the historical failure class documented in
    BUGFIX.md (the scaffold emitting a runner whose ``super().__init__()`` omitted the
    required ``platform_name``/``version`` arguments, or that was not a valid
    ``PlatformBase`` subclass at all) into a hard generation-time error instead of a
    runtime crash later.
    """
    import importlib.util

    repo_root = Path(__file__).resolve().parent
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))

    try:
        from PlatformBase import PlatformBase
    except Exception:  # noqa: BLE001 - environment problem, reported below
        return False, (
            "PlatformBase is not importable; run showet-scaffold.py from the "
            "showet repository root so the generated runner can be verified"
        )

    spec = importlib.util.spec_from_file_location(
        f"_scaffold_check_{platform_key}_{id(runner_path)}", str(runner_path)
    )
    if spec is None or spec.loader is None:
        return False, f"Could not load module from {runner_path}"
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except Exception as exc:  # noqa: BLE001 - surface any import/instantiation failure
        return False, f"Generated platform runner failed to import: {exc}"

    platform_classes = [
        obj
        for obj in vars(module).values()
        if isinstance(obj, type) and issubclass(obj, PlatformBase) and obj is not PlatformBase
    ]
    if not platform_classes:
        return False, "Generated file defines no PlatformBase subclass"
    try:
        instance = platform_classes[0]()
    except Exception as exc:  # noqa: BLE001
        return False, f"Generated platform runner failed to instantiate: {exc}"
    if instance.platform_name != platform_key:
        return False, f"platform_name {instance.platform_name!r} != expected {platform_key!r}"
    return True, f"verified: {platform_classes[0].__name__}(platform_name={instance.platform_name!r})"


def create_platform_runner(platform_key: str, output_dir: str):
    """Generate Platform_*.py file for new platform"""
    if platform_key not in PLATFORM_CONFIGS:
        print(f"❌ Unknown platform: {platform_key}")
        print(f"Available platforms: {', '.join(PLATFORM_CONFIGS.keys())}")
        return False

    config = PLATFORM_CONFIGS[platform_key]
    platform_name = platform_key.replace('_', ' ').title()
    platform_class = ''.join(word.capitalize() for word in platform_key.split('_'))

    # Get base directory
    base = Path(output_dir)

    # Refuse to clobber an existing runner for this platform. This prevents the
    # historical duplicate-runner failure (e.g. scaffolding emitting a second runner
    # for a platform that already has a canonical one) and guards against silent
    # overwrites of hand-maintained Platform_*.py files.
    runner_path = base / f"Platform_{platform_key}.py"
    if runner_path.exists():
        print(f"❌ Refusing to overwrite existing platform runner: {runner_path}")
        return False

    # Create platform runner
    runner_content = PLATFORM_TEMPLATE.format(
        platform_name=platform_name,
        platform_class=platform_class,
        platform_key=platform_key,
        core=config["core"],
        emulator=config["emulator"],
        shader=config["shader"],
        width=config["width"],
        height=config["height"]
    )

    runner_path.write_text(runner_content)
    print(f"✅ Created: {runner_path}")

    # Create nostalgist config
    config_content = CONFIG_TEMPLATE.format(platform_key=platform_key, **config)
    config_path = base / "nostalgist_configs" / f"{platform_key}.json"
    config_path.parent.mkdir(exist_ok=True)
    config_path.write_text(config_content)
    # Validate the generated JSON is well-formed before reporting success.
    try:
        json.loads(config_content)
    except json.JSONDecodeError as exc:
        print(f"❌ Generated nostalgist config is not valid JSON: {exc}")
        return False
    print(f"✅ Created: {config_path}")

    # Create shader stub
    shader_content = SHADER_TEMPLATE.format(
        platform_name=platform_name,
        scanline_density=200,
        scanline_intensity=0.1
    )
    shader_path = base / "shaders" / f"{platform_key}_scanlines.glsl"
    shader_path.parent.mkdir(exist_ok=True)
    shader_path.write_text(shader_content)
    print(f"✅ Created: {shader_path}")

    # Self-verify: the generated runner must actually be a usable PlatformBase subclass.
    ok, message = verify_platform_runner(runner_path, platform_key)
    if not ok:
        print(f"❌ {message}")
        return False
    print(f"✅ {message}")

    return True

def main():
    parser = argparse.ArgumentParser(
        description="Showet Platform Scaffold",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 showet-scaffold.py neogeo
  python3 showet-scaffold.py pcengine
  python3 showet-scaffold.py --list
        """
    )
    
    parser.add_argument('platform', nargs='?', help='Platform key to scaffold')
    parser.add_argument('--list', action='store_true', help='List available platforms')
    parser.add_argument('--dir', default='.', help='Output directory')
    
    args = parser.parse_args()
    
    if args.list:
        print("📋 Available platform templates:")
        for key in PLATFORM_CONFIGS:
            config = PLATFORM_CONFIGS[key]
            print(f"  {key:12} - core: {config['core']}, resolution: {config['width']}x{config['height']}")
        return
    
    if not args.platform:
        parser.print_help()
        return
    
    print(f"🚀 Scaffolding platform: {args.platform}")
    if create_platform_runner(args.platform, args.dir):
        print(f"\n🎉 {args.platform} platform added successfully!")
        print("   Don't forget to:")
        print("   - Add ROM files to the platform directory")
        print("   - Test with: python3 showet.py <demo_id> --platform {args.platform}")

if __name__ == "__main__":
    main()