// Neogeo CRT Shader
// Generated by showet-scaffold

precision mediump float;

uniform sampler2D u_texture;
varying vec2 v_texCoord;

void main() {
    vec2 coord = v_texCoord;
    
    // Simple scanlines
    float scanline = sin(coord.y * 200) * 0.1;
    
    vec4 color = texture2D(u_texture, coord);
    gl_FragColor = vec4(color.rgb - scanline, color.a);
}
