name: Gource visualisation

on:
  push:
    branches:
      - main

jobs:
  gource:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gource
        uses: nbprojekt/gource-action@v1
        with:
          gource_opts: >-
            --max-files 1000
            --key
            -800x600
            --highlight-users
            --filename-time 3
            --output-framerate 25
            -s 0.6
            --multi-sampling
            --auto-skip-seconds 0.1
            --stop-at-end
            --hide mouse,progress

      - name: Upscale + re-encode
        run: |
          ffmpeg -y -i ./gource/gource.mp4 \
            -c:v libx264 -crf 19 -level 3.1 -preset slow -tune film \
            -filter:v "scale=-1:720" -sws_flags lanczos \
            -c:a aac -b:a 128k \
            ./output.mp4

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-gource
          path: ./output.mp4
